### ISSUE TITLE
Can not install it

### ISSUE THREAD

**Issue by 4RSIM3R** [Timoteohss/slide_button#1]
I have some problem here, when i install this plugin

Couldn't read file LocalFile: 'C:\flutter\.pub-cache\hosted\pub.dartlang.org\slide_button-0.2.8\android\src\main\kotlin\com\timoteohss\slide_button\SlideButtonPlugin.kt' even though it exists. Please verify that this file has read permission and try again.

Anyone can help me?

**Comment by mvarendorff** [comment]
There is a typo in this package. You can manually fix this by going into your pub package cache and then to `hosted/pub.dartlang.org/slide_button-0.2.8/android/src/main/kotlin/com/timoteohss` and rename the `swipe_button` directory to `slide_button` and inside that folder rename `SwipeButtonPlugin.kt` to `SlideButtonPlugin.kt`.

While you are at it, you can probably also update the `build.gradle` file in the android directory of the package to use a newer Kotlin Gradle plugin version. My build complained that only 1.3.10 and higher are supported while this package still has 1.2.71 listed. Updating that as well fixed the build.

See #3 and #4.

**Comment by Timoteohss** [comment]
Fixed on 252533b, please update to version 0.2.9
