### ISSUE TITLE
slide_button doesn't have a main class 

### ISSUE THREAD

**Issue by tinvyhx** [Timoteohss/slide_button#6]
The plugin `slide_button` doesn't have a main class defined in /xxx/flutter/.pub-cache/hosted/pub.flutter-io.cn/slide_button-0.2.8/android/src/main/java/com/timoteohss/slide_button/SlideButtonPlugin.java or /Users/tv/dev/flutter/.pub-cache/hosted/pub.flutter-io.cn/slide_button-0.2.8/android/src/main/kotlin/com/timoteohss/slide_button/SlideButtonPlugin.kt. This is likely to due to an incorrect `androidPackage: com.timoteohss.slide_button` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile.

**Comment by DaniSalermi** [comment]
+1

**Comment by hiruthicShaSS** [comment]
Is there any solutions for the above error?

**Comment by semutKecil** [comment]
+1

**Comment by Timoteohss** [comment]
Shoul've been fixed on commit db10730, closing.
